In [3]:
import pandas as pd

In [ ]:
s = pd.Series([1,2,3,4,5],index=["a","b","c","d","e"])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [21]:
data = [[1,444,"abc"],
        [2,555,"def"],
        [3,666,"ghi"],
        [4,444,"xyz"]]
df = pd.DataFrame(data,columns=['col1','col2','col3'],index=["a","b","c","d"])
display(df)
df.columns=['id','sal','dep']
df

   col1  col2 col3
a     1   444  abc
b     2   555  def
c     3   666  ghi
d     4   444  xyz

   id  sal  dep
a   1  444  abc
b   2  555  def
c   3  666  ghi
d   4  444  xyz

In [24]:
df.dep.dtype

In [25]:
df['dep'] = df['dep'].astype('category')

In [26]:
df.dtypes

id        int64
sal       int64
dep    category
dtype: object

In [30]:
cols_cat = ['id', 'sal']
df[cols_cat] = df[cols_cat].astype('int64')

df.dtypes

id        int64
sal       int64
dep    category
dtype: object

In [4]:
data = [[1,444,"abc"],
        [2,555,"def"],
        [3,666,"ghi"],
        [4,444,"xyz"]]
df = pd.DataFrame(data,columns=['col1','col2','col3'],index=["a","b","c","d"])

In [33]:
df.head() #first 5
df.tail() #last 5
df.columns

Index(['col1', 'col2', 'col3'], dtype='str')

In [37]:
classifications = df.col2.nunique()
classifications

3

In [43]:
def get_range(df):
 x = df.max()
 y = df.min()
 return (x - y)
get_range(df.col1)

np.int64(3)

In [5]:
#very important 
df.col2.value_counts()

col2
444    2
555    1
666    1
Name: count, dtype: int64

In [6]:
df.info()

<class 'pandas.DataFrame'>
Index: 4 entries, a to d
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    4 non-null      int64
 1   col2    4 non-null      int64
 2   col3    4 non-null      str
dtypes: int64(2), str(1)
memory usage: 300.0+ bytes

In [ ]:
x1 = df.col2.values

array([444, 555, 666, 444])

In [8]:
df.values

array([[1, 444, 'abc'],
       [2, 555, 'def'],
       [3, 666, 'ghi'],
       [4, 444, 'xyz']], dtype=object)

In [10]:
df.replace(555, 'sara')

   col1  col2 col3
a     1   444  abc
b     2  sara  def
c     3   666  ghi
d     4   444  xyz